snowflake_profile:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: account  # from your Snowflake link
      user: usename
      password: password
      role: ACCOUNTADMIN               # or a custom role if set
      warehouse: NEWCOMPUTE_WH
      database: FINANCIAL_DB
      schema: RAW
      threads: 1
      client_session_keep_alive: false
